config/routes.rb
Rails.application.routes.draw do

  root 'exchange#index'

  get 'exchange/update' => 'exchange#update_rate', :as => "update_rate"
  get 'exchange/calculate_with_ajax' => 'exchange#calculate_with_ajax', :as => "calculate_with_ajax"
  get 'exchange/calculate' => 'exchange#calculate', :as => "calculate"
  get 'exchange/start_update' => 'exchange#start_update', :as => "start_update"

  

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  URL = "http://www.wego.co.id/hotel/carebear/exchange-rates.json"

  def self.get_update
    require 'open-uri'
    new_rates = JSON.parse open(URL).read

    all_rates = self.all
    if all_rates.blank?
      self.create(new_rates['rates'].map{|key, value| {currency: key, value: value}})
    else
      new_rates['rates'].each do |key, value|
        rate_rec = all_rates.where(["currency = ?", key]).first
        unless rate_rec.blank?
          rate_rec.update_attributes({value: value})
        else
          self.create({currency: key, value: value})
        end
      end
    end

    return self.all
  end

  def self.proces_calculating(currency_from_id, currency_to_id, amount)
    return 0 if amount.to_f == 0.0

    rates = self.where("id in (#{currency_from_id}, #{currency_to_id})")
    currency_from = rates.where("id = #{currency_from_id}").first
    currency_to = rates.where("id = #{currency_to_id}").first

    return amount.to_f * (currency_to.value.to_f/currency_from.value.to_f)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exchange_controller.rb
class ExchangeController < ApplicationController
  before_filter :automatic_update_rate, only: [:index, :update_rate, :calculate_with_ajax, :calculate]
  before_filter :prepare_rate_data, only: [:index, :update_rate, :calculate_with_ajax]

  def index
  end

  def update_rate
  end

  def calculate_with_ajax
  end

  def calculate
    result = Rate.proces_calculating(params[:currency_from_id], params[:currency_to_id], params[:amount])

    respond_to do |format|
      format.json { render json: {result: result}}
    end
  end

  def start_update
    @all_new_rates = Rate.get_update

    respond_to do |format|
      format.js
    end
  end

  protected
  def prepare_rate_data
    @rates = Rate.all
  end

  def automatic_update_rate
    last_update = Rate.last.try(:updated_at)
    if last_update.blank? || last_update + 1.days < Time.zone.now
      Rate.get_update
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/views/exchange/_rate_list.html.erb
              <tr>
                <td><%= rate_list_counter + 1 %></td>
                <td><%= rate_list.currency %></td>
                <td><%= rate_list.value %></td>
              </tr>

app/views/exchange/calculate_with_ajax.html.erb
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Exchange</h1>

        <h2 class="sub-header">Calcuation using Ajax</h2>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Amount</th>
                <th>From</th>
                <th>To</th>
                <th>result</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= text_field_tag "amount", '', placeholder: "0" %></td>
                <td>
                  <%= select_tag "currency_from", options_from_collection_for_select(@rates, 'id', 'currency'), {style: "width=200px"} %>
                </td>
                <td>
                  <%= select_tag "currency_to", options_from_collection_for_select(@rates, 'id', 'currency'), {style: "width=200px"} %>
                </td>
                <td id="result"></td>
                <td><%= link_to "Result", "#", class: 'btn btn-primary', id: "calcuation_with_ajax" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

app/views/exchange/index.html.erb
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Exchange</h1>

        <h2 class="sub-header">Calcuation using Javascript</h2>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Amount</th>
                <th>From</th>
                <th>To</th>
                <th>result</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= text_field_tag "amount", '', placeholder: "0" %></td>
                <td>
                  <%= select_tag "currency_from", options_from_collection_for_select(@rates, 'id', 'currency'), {style: "width=200px"} %>
                </td>
                <td>
                  <%= select_tag "currency_to", options_from_collection_for_select(@rates, 'id', 'currency'), {style: "width=200px"} %>
                </td>
                <td id="result"></td>
                <td><%= link_to "Result", "#", class: 'btn btn-primary', id: "calcuation_with_js" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <script >
        rates = <%= raw @rates.to_json %>;
      </script>

app/views/exchange/start_update.js.erb
$('table tbody').empty().append('<%=j render :partial => "rate_list", :collection => @all_new_rates %>');

app/views/exchange/update_rate.html.erb
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Update database Rate</h1>

        <div class="row placeholders">
          <div class=" placeholder">
            <h4>Do you want to update rate?</h4>
            <span><%= link_to "Start", "#", class: 'btn btn-primary', id: "start_update" %></span>
            <p id="status_update"></p>
          </div>
        </div>

        <h2 class="sub-header">Rate</h2>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Currency</th>
                <th>rate</th>
              </tr>
            </thead>
            <tbody>
              <%#= render :partial => "rate_list", :collection => @rates %>
            </tbody>
          </table>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExchangeRates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Exchange Rate</a>
        </div>
      </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Exchange with js', root_path %></li>
          <li class="<%= 'active' if current_page?(calculate_path) %>"><%= link_to 'Exchange with ajax', calculate_with_ajax_path %></li>
          <li class="<%= 'active' if current_page?(update_rate_path) %>"><%= link_to "Update Currency", update_rate_path %></a></li>

        </ul>
      </div>

      <%= yield %>
      
    </div>
  </div>

  

</body>
</html>